name = "eatwhat-api"
main = "apps/worker/src/index.ts"
compatibility_date = "2025-01-01"

[vars]
ADMIN_TOKEN = "need-"

[[d1_databases]]
binding = "DB"
database_name = "eatwhat"
database_id = "081b29cb-7d2f-44d5-a539-eac87335d228"
